/*
 * This Java source file was generated by the Gradle 'init' task.
 */

public class App {
  public String getGreeting() {
    return "Hello World!";
  }

  public static void main(String[] args) {
    App greeting = new App();
    System.out.println(greeting.getGreeting());
  }
}
