/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package firstyearportfolio;

import java.util.Scanner;

public class App {
    public int getGreeting() {
        int value = 0;
        try (Scanner key = new Scanner(System.in)) {
            System.out.println("This is a collection of the different classes that I have");
            System.out.println("Developed in the first year of my college CS program.");
            System.out.println("A combination of options will be visible to try out those");
            System.out.println("Different classes.\n");
            System.out.println("Please select 1 through 4 to see the different option. Press 5 for More.");
            if (key.hasNextLine()) {
                value = Integer.valueOf(key.nextLine());
                switch (value) {
                    case 1:
                        MathFormula.exe();
                }
            }
        }
        return value;
    }

    public static void main(String[] args) {
        System.out.println(new App().getGreeting());
    }
}
